forge "http://forge.puppetlabs.com"

# mod 'puppetlabs/stdlib'
mod 'puppetlabs/git', '0.0.3'

mod 'dhoppe/vim', '0.0.11'

mod 'willdurand/composer', '0.0.5'


mod 'puppetlabs/mysql', '2.0.1'

# mod 'ntp',
#   :git => 'git://github.com/puppetlabs/puppetlabs-ntp.git'

# mod 'apt',
#   :git => 'https://github.com/puppetlabs/puppetlabs-apt.git',
#   :ref => 'feature/master/dans_refactor'
